config:
    build_jobs: 32
    install_missing_compilers: false
    install_tree:
      root: /appl/lumi/spack/23.03/0.20.0/opt/spack
      projections:
        all: '{name}-{version}-{hash:7}'
    build_language: C
    db_lock_timeout: 10

