config:
    build_jobs: 48
    install_missing_compilers: false
    install_tree:
      root: /appl/lumi/spack/23.09/0.21.0/opt/spack
      projections:
        all: '{name}-{version}-{hash:7}'
    build_language: C
    db_lock_timeout: 10

